apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-pvc
  namespace: siyuan
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
